# Generated by Django 4.2.23 on 2025-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '물건', 'verbose_name_plural': '물건 관리'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': '구매 기록', 'verbose_name_plural': '구매 기록'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '학생', 'verbose_name_plural': '학생 관리'},
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
    ]
