# Generated by Django 4.2.23 on 2025-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_item_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[(3, '3학년'), (4, '4학년'), (5, '5학년'), (6, '6학년')], default=3),
        ),
    ]
