# Generated by Django 4.2.23 on 2026-01-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_student_options_student_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '학생', 'verbose_name_plural': '학생 관리'},
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
    ]
