# Generated by Django 4.2.23 on 2026-01-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_student_options_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
