# Generated by Django 4.2.23 on 2026-01-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_purchase_is_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedPurchase',
            fields=[
            ],
            options={
                'verbose_name': '배송 완료 목록',
                'verbose_name_plural': '배송 완료 목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('market.purchase',),
        ),
        migrations.CreateModel(
            name='PendingPurchase',
            fields=[
            ],
            options={
                'verbose_name': '배송 전 목록',
                'verbose_name_plural': '배송 전 목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('market.purchase',),
        ),
    ]
